style(.clang-format): update formatting rules based on LLVM style guide and adjust indentation and spacing rules.
chore(compile_commands.json): remove unnecessary flags from gcc arguments
feat(compile_commands.json): add new source files to compilation process

feat: add hashing dump and load functionality

Add hashing dump and load functionality to the project. The dump functionality allows for the dumping of data to a file, while the load functionality allows for the loading of data from a file. The dump and load functionality are templated and support arithmetic types. The dump and load functionality have been tested with a file containing 100 integers in both Unix and DOS formats.

feat(load/dump): add tests for loading and dumping files

Add tests for loading and dumping files in the hashing and sorting modules.
The tests include loading and dumping files in both Unix and DOS formats.
The tests ensure that the loaded data matches the expected data and that the
dumped file matches the original file.

feat(load_tests.cpp): add tests for aon::sorting::load function with 100 integers from files with unix and dos line endings

diff --git a/scripts/hot-reload b/scripts/hot-reload
--- a/scripts/hot-reload
+++ b/scripts/hot-reload
@@ -2,22 +2,25 @@
 
 # print the usage message
 usage() {
-    echo -e "Usage: $0 [target]" 1>&2
-    exit 1
+	echo -e "Usage: $0 [target]" 1>&2
+	exit 1
 }
 command_exists() {
-    if ! command -v """$1" >/dev/null 2>&1; then
-        echo "I require the command ""$1 but it's not installed. Abort."
-        exit 1
-    fi
+	if ! command -v """$1" >/dev/null 2>&1; then
+		echo "I require the command ""$1 but it's not installed. Abort."
+		exit 1
+	fi
 }
 
 # depts
 for i in "nodemon" "ccache"; do
-    command_exists "$i"
+	command_exists "$i"
 done
 
-# get the argument target or use default(midirc)
-target=${1:-midirc}
+target=${1}
+
+if [ "$target" = "" ]; then
+	usage
+fi
 
 nodemon -e cc,h,js,cpp,hpp --exec "xmake build && xmake run -w . -- $target"
